[package]
name = "P2P-ImageSharing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
io = "0.0.2"
net = "0.1.0"
thread = "0.1.0"
time = "0.3.30"
